<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container3zx3qBD\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container3zx3qBD/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container3zx3qBD.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container3zx3qBD\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container3zx3qBD\App_KernelDevDebugContainer([
    'container.build_hash' => '3zx3qBD',
    'container.build_id' => '2fd552fe',
    'container.build_time' => 1613637861,
], __DIR__.\DIRECTORY_SEPARATOR.'Container3zx3qBD');
