<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerJCTomxI\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerJCTomxI/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerJCTomxI.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerJCTomxI\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerJCTomxI\App_KernelDevDebugContainer([
    'container.build_hash' => 'JCTomxI',
    'container.build_id' => '158bc05b',
    'container.build_time' => 1612868600,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerJCTomxI');
