<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerPOKhGRE\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerPOKhGRE/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerPOKhGRE.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerPOKhGRE\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerPOKhGRE\App_KernelDevDebugContainer([
    'container.build_hash' => 'POKhGRE',
    'container.build_id' => 'e1d3243a',
    'container.build_time' => 1613847825,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerPOKhGRE');
