<?php

namespace ContainerN4xn8Iz;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_ABCDnlaService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.aBCDnla' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.aBCDnla'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'authenticationUtils' => ['privates', '.errored.dg2pc80', NULL, 'Cannot determine controller argument for "App\\Controller\\SecurityController::login()": the $authenticationUtils argument is type-hinted with the non-existent class or interface: "Symfony\\Component\\Security\\Http\\Authentication\\AuthenticationUtils".'],
        ], [
            'authenticationUtils' => '?',
        ]);
    }
}
