<?php

namespace ContainerN4xn8Iz;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_Errored_Dg2pc80Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored.dg2pc80' shared service.
     *
     * @return \Symfony\Component\Security\Http\Authentication\AuthenticationUtils
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot determine controller argument for "App\\Controller\\SecurityController::login()": the $authenticationUtils argument is type-hinted with the non-existent class or interface: "Symfony\\Component\\Security\\Http\\Authentication\\AuthenticationUtils".');
    }
}
