<?php

namespace ContainerOgb0U9y;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_Errored_07ikganService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored.07ikgan' shared service.
     *
     * @return \Symfony\Component\Security\Guard\GuardAuthenticatorHandler
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot determine controller argument for "App\\Controller\\RegisterController::register()": the $guardHandler argument is type-hinted with the non-existent class or interface: "Symfony\\Component\\Security\\Guard\\GuardAuthenticatorHandler".');
    }
}
