<?php

namespace ContainerSO9MRVB;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSluggerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'slugger' shared service.
     *
     * @return \stdClass
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('You cannot use the "slugger" service since the Translation contracts are not installed. Try running "composer require symfony/translation".');
    }
}
