<?php

namespace Container8vloqaR;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_Errored_Y_L0vFpService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored.y.l0vFp' shared service.
     *
     * @return \App\Security\LoginAuthenticator
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot determine controller argument for "App\\Controller\\RegisterController::register()": the $authenticator argument is type-hinted with the non-existent class or interface: "App\\Security\\LoginAuthenticator".');
    }
}
